### ISSUE TITLE
Add Twitter and Mastodon handles to journals.csv

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#1]

**Comment by larsvilhuber** [comment]
@korenmiklos assuming this Jekyll theme has Font-Awesome icons, I also added display on the journals page.

**Comment by larsvilhuber** [comment]
This jekyll does NOT have FA icons...

**Comment by larsvilhuber** [comment]
Now [9f4a83e](https://github.com/social-science-data-editors/DCAS/commit/9f4a83e639d4ea9c42f3ae79f00a97558765a50e) it does.
