### ISSUE TITLE
Add plausible analytics code

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#19]
<script defer data-domain="codedatastandard.org" src="https://plausible.io/js/script.js"></script>

Add this head.

**Comment by korenmiklos** [comment]
@larsvilhuber Can you try poking around the website? I added the code and it works with Safari, but my Brave's adblocker blocks it.

**Comment by larsvilhuber** [comment]
Works on Firefox mobile. What doesn't work on Brave?

--
Lars Vilhuber
On mobile device
________________________________

**Comment by korenmiklos** [comment]
It was only the analytics .js code that did not get called. But now it works.
