### ISSUE TITLE
Create badge for endorsement

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#20]
using shields.io. Related to #6

**Comment by korenmiklos** [comment]
Logo: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAOCAYAAAEeda/MAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABvJJREFUSA1dVmuMXFUd///PvTP7pLszw7a7O3d2l507pU1t/VBAJVHqIwRIQAWigdAEQVBjoqaJiv0gNSZV1PCBSLB+UD74ChI0aRNNDNlCImLTphiyge7MsI+Z6W5357Hbfc7MPef4+9/ZW4knuXPO+b/fZ6ju+VOWiGue/y5hNUZuGa+NZjNyps1Mzlo65soZBNOyUzXt/0D2upd74Zp3yxE51zK5WdmFSgsHxL4hd+xF+pCI4gZECiJarbH9Vj4AVcPzQxzb8VutBshdmOH65OTAnsBdFYZNY2mgnGc5Q/JOP6suJbcqvBCgrGuj2TtxvyZnkYpzRXZ8DsybaaT946FJbagVoqqXe01MFCK5g+hZ2Zcy2Y800vs/KudwQWWwOOwPrXj+XRFMhLwCyc1MR9hqxs+ueTmr7PgBkf6H4aVC7WblnLdjt9qV8YMjLiv6EpGOK0WNTPYLA8opBGT/xbWM/zxZO9zF6pE+IHn+CotJDS/7O0v8MM4LTPZCPzuPbJH+4mCpeBa+a5i7gn1Q8KlyIRtZJlFdN+YtwItJ5RwPoxYhkcSlQUftawR8QCn9vtJ6YnBxtgQiE9F08lh58SbFT8eRCXFxnczpudLAqdvoUls8ahhN/TB2XZsTYfCEeSXjP8BMiVVjnhm6euUKtFOX685Fwmte7ozQ1UdLdyBHT7ec9rAoa2o+AJdPToxf9wXfMOYXyXKBrwd0EHl+npGA85ZszVHOdwcXZj4QIrgHXQCms7/F6T6ArjpKPTSwMPM/hfCWmJoIz7jwRKuW9n8D+APE9nKyVLxbWaZlIH1jTLGWzv0RwqW+rCSzR6nHcXwdsL5+xFS8EeU139/jMO2LMY/h7ggshHu5CxAOHnqBLH8cebyHpjp15qAof7qKchcGeHVxZ7d8LtLRGBhuLOAVEvwWimMNu6l52XPCIwS4W3yNiPhUx9hOSFaGDvXFuprrhumeHuK/b1vbgvtdEfGHd0nshtE/RvhGblLqq5JsUVL1sk/2sTqDWqRNaxrgT0ZJZtMbDKFUrDZ8DcJtL3M8EgrmUEBYQenc11HflKoUfwgBT+3AZ8T9YaJjvDzQ/XJvKc9bVn8NghPwZj5UILGNaZ1H5fDeSv4d8J/YtHYbYfu+KFkcHe2pp/0Hmc4HcUUvQehmpLwNBaiIPwtuZK31HTsx0Z0sF38NowLIbWG6SGda2jKGoF2mG/JOEts3e1l9shsdCgKqG33ZuMF9gya+eN3oB1PlzFlRUvVKTySUc8ZZGI3VvPJGQskUggRZN/fHdxV07qJIRtkaSgokP0M9h9NTQiQU+BFdVM/kfoU8SRgI1YQMh2h0o6UAFFsWwWb+SqKUfxlXIdEXjx6N3XbpUhtR+WXKcb7Z0DpIOK5b18EphPpHEV7kRzx1b/KwJfU2HOgVeGg3kC3YKCOpbtphbwruxkJknpLhDEU74RxDTiMknoFHBYbcbW1juFcz/ukIF+3gewb4J+UuhnT23Xcl4z+hMarQBU3QbOALZHQ1MESEbrdjwrJY9rI+6Nrr0AO6OcFHqzqSOwjdn5d7J3S7mMjzNW8yF5CaAdh0MasWmcOuiS22OZC3gpF6hS74zFClOGURWUZkRQT4Ie8YjD4vZaJ3YWEGqpn9t8esveACgRr8T72bPpbcsbNxViOIqNZkDu4tf5CPbCh5Xk8fdc8ju0PSFFhtSP8LE/+VnfbfEnNzq6Lv/x0QgF3ad6TPjW0VYMkw2hQlpe81xp3tc8z76EAR1sIc359YnJ3HTQbXjVkuyGjtKrCrY2MJbeJFyEvAK1QFHU4tFKaXM7lPoTbewENOMHJhaaArd2h6uiV8kCG2mPqof79VdBL322GLI70kylB+VA+CE3ht5UHtfHToUDjU4u7WtwaUwqwn6YdKvZun5H2A8dOYnoTnPG4c9ROgwyXDUGREd9nBG5aCnAMT/0ecORG+lpa/IcZLhPeW8m82rX22FyHowVQeXm2eE3os4RX1lLxaOIse+QQ+V+bdjuNMAhGs6kDcPM2dUcNpZhtgvB1Byj4rHiYdh+ravJ4q5z8HhjAzIhD0/04p546a0U3Mwi449S7q5TKi1Q2Vd+5RypOmrmlz/1Alf66K96oXT4pYs2PNa6ly8aEpOPtpjC3AwuzJe+cy3xUH36bVPwfN95Yz2S8PsfunNoTieS8h8ecwfTbgl/xFGId9qqb1c/KP7j3QYBiSYcsNjOR3QPz7VKXwthgcKZHzK2hK+VMiZ/w1OA6vHoPhOVzx1NEGHJ+HnFdTpcJLYfq97L2QhfTzNmhnEuXCtwEP+UUGZIeBkZKNxbdfxAs6AjAmqz2ZXCj+c2NiYrgZuDJE7sY3Bg5lLS8iPa8mKoXnRMd/AbCzW8/QF3NOAAAAAElFTkSuQmCC`

**Comment by korenmiklos** [comment]
The badge is here: ![](https://img.shields.io/badge/compliant-v1.0-brightgreen?style=plastic&logoWidth=40&labelColor=white&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAOCAYAAAEeda/MAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABvJJREFUSA1dVmuMXFUd///PvTP7pLszw7a7O3d2l507pU1t/VBAJVHqIwRIQAWigdAEQVBjoqaJiv0gNSZV1PCBSLB+UD74ChI0aRNNDNlCImLTphiyge7MsI+Z6W5357Hbfc7MPef4+9/ZW4knuXPO+b/fZ6ju+VOWiGue/y5hNUZuGa+NZjNyps1Mzlo65soZBNOyUzXt/0D2upd74Zp3yxE51zK5WdmFSgsHxL4hd+xF+pCI4gZECiJarbH9Vj4AVcPzQxzb8VutBshdmOH65OTAnsBdFYZNY2mgnGc5Q/JOP6suJbcqvBCgrGuj2TtxvyZnkYpzRXZ8DsybaaT946FJbagVoqqXe01MFCK5g+hZ2Zcy2Y800vs/KudwQWWwOOwPrXj+XRFMhLwCyc1MR9hqxs+ueTmr7PgBkf6H4aVC7WblnLdjt9qV8YMjLiv6EpGOK0WNTPYLA8opBGT/xbWM/zxZO9zF6pE+IHn+CotJDS/7O0v8MM4LTPZCPzuPbJH+4mCpeBa+a5i7gn1Q8KlyIRtZJlFdN+YtwItJ5RwPoxYhkcSlQUftawR8QCn9vtJ6YnBxtgQiE9F08lh58SbFT8eRCXFxnczpudLAqdvoUls8ahhN/TB2XZsTYfCEeSXjP8BMiVVjnhm6euUKtFOX685Fwmte7ozQ1UdLdyBHT7ec9rAoa2o+AJdPToxf9wXfMOYXyXKBrwd0EHl+npGA85ZszVHOdwcXZj4QIrgHXQCms7/F6T6ArjpKPTSwMPM/hfCWmJoIz7jwRKuW9n8D+APE9nKyVLxbWaZlIH1jTLGWzv0RwqW+rCSzR6nHcXwdsL5+xFS8EeU139/jMO2LMY/h7ggshHu5CxAOHnqBLH8cebyHpjp15qAof7qKchcGeHVxZ7d8LtLRGBhuLOAVEvwWimMNu6l52XPCIwS4W3yNiPhUx9hOSFaGDvXFuprrhumeHuK/b1vbgvtdEfGHd0nshtE/RvhGblLqq5JsUVL1sk/2sTqDWqRNaxrgT0ZJZtMbDKFUrDZ8DcJtL3M8EgrmUEBYQenc11HflKoUfwgBT+3AZ8T9YaJjvDzQ/XJvKc9bVn8NghPwZj5UILGNaZ1H5fDeSv4d8J/YtHYbYfu+KFkcHe2pp/0Hmc4HcUUvQehmpLwNBaiIPwtuZK31HTsx0Z0sF38NowLIbWG6SGda2jKGoF2mG/JOEts3e1l9shsdCgKqG33ZuMF9gya+eN3oB1PlzFlRUvVKTySUc8ZZGI3VvPJGQskUggRZN/fHdxV07qJIRtkaSgokP0M9h9NTQiQU+BFdVM/kfoU8SRgI1YQMh2h0o6UAFFsWwWb+SqKUfxlXIdEXjx6N3XbpUhtR+WXKcb7Z0DpIOK5b18EphPpHEV7kRzx1b/KwJfU2HOgVeGg3kC3YKCOpbtphbwruxkJknpLhDEU74RxDTiMknoFHBYbcbW1juFcz/ukIF+3gewb4J+UuhnT23Xcl4z+hMarQBU3QbOALZHQ1MESEbrdjwrJY9rI+6Nrr0AO6OcFHqzqSOwjdn5d7J3S7mMjzNW8yF5CaAdh0MasWmcOuiS22OZC3gpF6hS74zFClOGURWUZkRQT4Ie8YjD4vZaJ3YWEGqpn9t8esveACgRr8T72bPpbcsbNxViOIqNZkDu4tf5CPbCh5Xk8fdc8ju0PSFFhtSP8LE/+VnfbfEnNzq6Lv/x0QgF3ad6TPjW0VYMkw2hQlpe81xp3tc8z76EAR1sIc359YnJ3HTQbXjVkuyGjtKrCrY2MJbeJFyEvAK1QFHU4tFKaXM7lPoTbewENOMHJhaaArd2h6uiV8kCG2mPqof79VdBL322GLI70kylB+VA+CE3ht5UHtfHToUDjU4u7WtwaUwqwn6YdKvZun5H2A8dOYnoTnPG4c9ROgwyXDUGREd9nBG5aCnAMT/0ecORG+lpa/IcZLhPeW8m82rX22FyHowVQeXm2eE3os4RX1lLxaOIse+QQ+V+bdjuNMAhGs6kDcPM2dUcNpZhtgvB1Byj4rHiYdh+ravJ4q5z8HhjAzIhD0/04p546a0U3Mwi449S7q5TKi1Q2Vd+5RypOmrmlz/1Alf66K96oXT4pYs2PNa6ly8aEpOPtpjC3AwuzJe+cy3xUH36bVPwfN95Yz2S8PsfunNoTieS8h8ecwfTbgl/xFGId9qqb1c/KP7j3QYBiSYcsNjOR3QPz7VKXwthgcKZHzK2hK+VMiZ/w1OA6vHoPhOVzx1NEGHJ+HnFdTpcJLYfq97L2QhfTzNmhnEuXCtwEP+UUGZIeBkZKNxbdfxAs6AjAmqz2ZXCj+c2NiYrgZuDJE7sY3Bg5lLS8iPa8mKoXnRMd/AbCzW8/QF3NOAAAAAElFTkSuQmCC)

**Comment by korenmiklos** [comment]
This looks nicer: ![](https://img.shields.io/badge/compliant-v1.0-brightgreen?style=plastic&logoWidth=40&labelColor=white&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNjQuOTYgMTA3LjIxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2VkMWMyNDt9PC9zdHlsZT48L2RlZnM+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTU4LjUyLDc4LjkxYy41OCwwLDEuMTUsLjExLDEuNzMsLjMyLC41OCwuMjIsMS4xMywuNTksMS42NiwxLjEybDkuNjUsMTAuMTVjLTQuMjIsNS41Mi05LjUyLDkuNjgtMTUuODgsMTIuNDktNi4zNiwyLjgxLTEzLjg4LDQuMjEtMjIuNTcsNC4yMS03Ljk3LDAtMTUuMTEtMS4zNi0yMS40Mi00LjA3LTYuMzEtMi43MS0xMS42Ni02LjQ2LTE2LjA2LTExLjIzLTQuMzktNC43OC03Ljc2LTEwLjQ0LTEwLjEyLTE2Ljk5LTIuMzUtNi41NS0zLjUzLTEzLjY3LTMuNTMtMjEuMzVzMS4zNC0xNS4wMSw0LjAzLTIxLjU2YzIuNjktNi41NSw2LjQ0LTEyLjIsMTEuMjctMTYuOTYsNC44Mi00Ljc1LDEwLjYtOC40NSwxNy4zMi0xMS4wOSw2LjcyLTIuNjQsMTQuMTQtMy45NiwyMi4yNS0zLjk2LDMuOTQsMCw3LjY0LC4zNSwxMS4xMiwxLjA0LDMuNDgsLjcsNi43MywxLjY2LDkuNzYsMi44OCwzLjAyLDEuMjIsNS44MSwyLjY5LDguMzUsNC4zOSwyLjU0LDEuNyw0LjgsMy41OSw2Ljc3LDUuNjVsLTguMjEsMTEuMDJjLS41MywuNjctMS4xNSwxLjI4LTEuODcsMS44NC0uNzIsLjU1LTEuNzMsLjgzLTMuMDIsLjgzLS44NiwwLTEuNjgtLjE5LTIuNDUtLjU4LS43Ny0uMzgtMS41OC0uODUtMi40NS0xLjQtLjg2LS41NS0xLjgxLTEuMTUtMi44NC0xLjgtMS4wMy0uNjUtMi4yNi0xLjI1LTMuNjctMS44LTEuNDItLjU1LTMuMDctMS4wMi00Ljk3LTEuNC0xLjktLjM4LTQuMTItLjU4LTYuNjYtLjU4LTQuNDIsMC04LjQ1LC43OC0xMi4xLDIuMzQtMy42NSwxLjU2LTYuNzgsMy43OS05LjQsNi43LTIuNjIsMi45LTQuNjYsNi40Mi02LjEyLDEwLjU1LTEuNDYsNC4xMy0yLjIsOC43Ni0yLjIsMTMuOXMuNzMsMTAuMTUsMi4yLDE0LjMzYzEuNDYsNC4xOCwzLjQ2LDcuNjksNS45OCwxMC41NSwyLjUyLDIuODYsNS40Niw1LjAzLDguODIsNi41MiwzLjM2LDEuNDksNi45NiwyLjIzLDEwLjgsMi4yMywyLjIxLDAsNC4yMi0uMTEsNi4wNS0uMzIsMS44Mi0uMjIsMy41Mi0uNTksNS4wOC0xLjEyLDEuNTYtLjUzLDMuMDUtMS4yMSw0LjQ2LTIuMDUsMS40Mi0uODQsMi44NC0xLjg4LDQuMjgtMy4xMywuNTgtLjQ4LDEuMi0uODgsMS44Ny0xLjE5LC42Ny0uMzEsMS4zNy0uNDcsMi4wOS0uNDdaIi8+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMzU3LjQ3LDIyLjQ2Yy0uNzIsMS4xNS0xLjQ3LDIuMDItMi4yNywyLjU5LS43OSwuNTgtMS44MSwuODYtMy4wNiwuODYtMS4xMSwwLTIuMjktLjM1LTMuNTYtMS4wNC0xLjI3LS42OS0yLjcxLTEuNDgtNC4zMi0yLjM0LTEuNjEtLjg2LTMuNDQtMS42NC01LjUxLTIuMzQtMi4wNi0uNy00LjQyLTEuMDQtNy4wNi0xLjA0LTQuNTYsMC03Ljk2LC45Ny0xMC4xOSwyLjkyLTIuMjMsMS45NC0zLjM1LDQuNTctMy4zNSw3Ljg4LDAsMi4xMSwuNjcsMy44NiwyLjAyLDUuMjYsMS4zNCwxLjM5LDMuMTEsMi41OSw1LjI5LDMuNiwyLjE4LDEuMDEsNC42OCwxLjkzLDcuNDksMi43NywyLjgxLC44NCw1LjY4LDEuNzgsOC42LDIuODEsMi45MywxLjAzLDUuOCwyLjI0LDguNiwzLjY0LDIuODEsMS4zOSw1LjMsMy4xNyw3LjQ5LDUuMzMsMi4xOCwyLjE2LDMuOTUsNC43OSw1LjI5LDcuODgsMS4zNCwzLjEsMi4wMiw2LjgzLDIuMDIsMTEuMiwwLDQuODUtLjg0LDkuMzgtMi41MiwxMy42MS0xLjY4LDQuMjItNC4xMiw3LjkxLTcuMzEsMTEuMDUtMy4xOSwzLjE0LTcuMTMsNS42Mi0xMS44MSw3LjQyLTQuNjgsMS44LTEwLDIuNy0xNS45NSwyLjctMy4yNiwwLTYuNTktLjM0LTkuOTctMS4wMS0zLjM4LS42Ny02LjY2LTEuNjItOS44My0yLjg0LTMuMTctMS4yMi02LjE0LTIuNjgtOC45My00LjM2LTIuNzgtMS42OC01LjIxLTMuNTUtNy4yNy01LjYybDcuMi0xMS4zOGMuNTMtLjg2LDEuMjctMS41NiwyLjIzLTIuMDksLjk2LS41MywxLjk5LS43OSwzLjEtLjc5LDEuNDQsMCwyLjg5LC40Niw0LjM2LDEuMzcsMS40NiwuOTEsMy4xMiwxLjkyLDQuOTcsMy4wMiwxLjg1LDEuMSwzLjk3LDIuMTEsNi4zNywzLjAyLDIuNCwuOTEsNS4yMywxLjM3LDguNSwxLjM3LDQuNDIsMCw3Ljg1LS45NywxMC4zLTIuOTIsMi40NS0xLjk0LDMuNjctNS4wMywzLjY3LTkuMjUsMC0yLjQ1LS42Ny00LjQ0LTIuMDItNS45OC0xLjM0LTEuNTQtMy4xMS0yLjgxLTUuMjktMy44Mi0yLjE5LTEuMDEtNC42Ny0xLjktNy40NS0yLjY2LTIuNzgtLjc3LTUuNjQtMS42Mi04LjU3LTIuNTYtMi45My0uOTQtNS43OS0yLjA5LTguNTctMy40Ni0yLjc4LTEuMzctNS4yNy0zLjE3LTcuNDUtNS40LTIuMTktMi4yMy0zLjk1LTUuMDItNS4yOS04LjM1LTEuMzQtMy4zNC0yLjAyLTcuNDUtMi4wMi0xMi4zNSwwLTMuOTQsLjc5LTcuNzgsMi4zOC0xMS41MnMzLjkxLTcuMDgsNi45OC0xMC4wMWMzLjA3LTIuOTMsNi44NC01LjI3LDExLjMtNy4wMiw0LjQ2LTEuNzUsOS41OC0yLjYzLDE1LjM0LTIuNjMsMy4yMiwwLDYuMzUsLjI1LDkuNCwuNzYsMy4wNSwuNSw1Ljk0LDEuMjUsOC42OCwyLjIzLDIuNzMsLjk4LDUuMjksMi4xNiw3LjY3LDMuNTMsMi4zOCwxLjM3LDQuNSwyLjkyLDYuMzcsNC42NGwtNi4wNSwxMS4zWiIvPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTY3LjAzLDMzLjA2Yy0yLjYyLTYuNDEtNi4zLTExLjk0LTExLjA1LTE2LjYtNC43NS00LjY2LTEwLjQ4LTguMy0xNy4xNy0xMC45NC02LjctMi42NC0xNC4xMi0zLjk2LTIyLjI4LTMuOTZsLTE1LjgzLC4wMkMuMzEsMS41OCwwLDEuOSwwLDIuMjhWMTUuNjZDMCwxOC4yMSwyLjA2LDIwLjI3LDQuNjEsMjAuMjdjNC44OSwwLDExLjkyLDAsMTEuOTIsMCw0LjY2LDAsOC44MSwuNzgsMTIuNDYsMi4zNCwzLjY1LDEuNTYsNi43MywzLjc5LDkuMjUsNi43LDIuNTIsMi45LDQuNDUsNi40NCw1LjgsMTAuNjIsMS4zNCw0LjE4LDIuMDIsOC44NiwyLjAyLDE0LjA0cy0uNjcsOS45NC0yLjAyLDE0LjExYy0xLjM0LDQuMTgtMy4yOCw3LjcyLTUuOCwxMC42Mi0yLjUyLDIuOS01LjYsNS4xNC05LjI1LDYuNy0zLjY1LDEuNTYtNy44LDIuMzQtMTIuNDYsMi4zNCwwLDAtNy4wMSwwLTExLjksMC0yLjU2LDAtNC42MywyLjA3LTQuNjMsNC42M3YxMy41MmMwLC4zOSwuMzIsLjcsLjcsLjdsMTUuODItLjEyYzguMTYsMCwxNS41OS0xLjMxLDIyLjI4LTMuOTIsNi43LTIuNjIsMTIuNDItNi4yNiwxNy4xNy0xMC45NCw0Ljc1LTQuNjgsOC40NC0xMC4yMiwxMS4wNS0xNi42MywyLjYyLTYuNDEsMy45Mi0xMy40LDMuOTItMjAuOTlzLTEuMzEtMTQuNTEtMy45Mi0yMC45MloiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0yODQuNjcsMTA1LjIzaC0xOS41OGMtMi4xMSwwLTMuODQtLjQ4LTUuMTgtMS40NC0xLjM0LS45Ni0yLjMtMi4yMy0yLjg4LTMuODJsLTIwLjMtNTYuMTZjLS45MS0yLjQ1LTEuODQtNS4xMS0yLjc3LTcuOTktLjk0LTIuODgtMS44MS01LjktMi42My05LjA3LS42NywzLjE3LTEuNDUsNi4xOS0yLjM0LDkuMDctLjg5LDIuODgtMS43Niw1LjU0LTIuNjMsNy45OWwtMjAuMTYsNTYuMTZjLS40OCwxLjM0LTEuNDIsMi41Ni0yLjgxLDMuNjQtMS4zOSwxLjA4LTMuMSwxLjYyLTUuMTEsMS42MmgtMTkuNzNMMjIwLjU5LC4zM2gyMi4wM2w0Mi4wNSwxMDQuOVoiLz48L3N2Zz4=)

**Comment by larsvilhuber** [comment]
@korenmiklos Can you provide the Markdown code for this? Your pasted images do not show, or show as embedded.
