### ISSUE TITLE
Clarify data sharing

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#21]
We have removed "to the extend allowed by the law and other agreements" from Rules 1 and 2. This can create confusion as to what has to be shared. REStud directors asked about how this applies to confidential data so this is not abundantly clear.

Either add this back, or add a "footnote" to the rules that DCAS does not overwrite laws and other agreements. @larsvilhuber ?

**Comment by larsvilhuber** [comment]
Hm. @korenmiklos Maybe we should  move Rule 6 to Rule 1. As the very first statement, tell folks how it is... Then add "Exceptions are documented as part of Rule 1." to both Rule 2 and 3 (under new numbering).

**Comment by korenmiklos** [comment]
@larsvilhuber pls see https://github.com/larsvilhuber/DCAS-test/commit/60a07dcb87a346bab763c1aa43d739ef4218aa2f#commitcomment-92804538

**Comment by korenmiklos** [comment]
How about Rule 16? Was that not sufficient to cover this case? With the new wording, is there still a need for 16?

**Comment by korenmiklos** [comment]
Resolved in #24
