### ISSUE TITLE
Link to template README

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#28]
Ideally, I would change its URL to templatereadme.org, but we can do that later.

**Comment by larsvilhuber** [comment]
I do not like creating custom URLs for each of these things. They are not robust. In 1 year's time, you will remember to pay for the domain. In 5 years time, you will have forgotten. The current Github.io is more robust, and the DOI is perfectly robust. I suggest sticking with that. The templatereadme.org can be reserved for the interactive one.

**Comment by korenmiklos** [comment]
For now it is fine, but I disagree about the longer run. We have no control over github domain names. Just a couple years ago, they changed from username.github.com to username.github.io. We may even want to change hosts if Elon Musk takes over GitHub :)

**Comment by larsvilhuber** [comment]
I give you that they have changed once in 12+ years (9 years ago), and then redirected domains for another 8 years. Do you think that you will want to do this for the next 10 years? Not likely. Maybe one site. Not multiple sites.

--
Lars Vilhuber
On mobile device
________________________________
