### ISSUE TITLE
Are we fine with authors, incl. author order, to be published on Zenodo

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#29]
Koren, M., L. Vilhuber, J. Llull, and M. Connolly. 2022. “Data and Code Availability Standard [Version 1.0rc2].” Website. https://datacodestandard.org <DOI from Zenodo>

**Comment by larsvilhuber** [comment]
I suggest Koren, then alphabetical.

Use the CFF to handle this.

--
Lars Vilhuber
On mobile device
________________________________

**Comment by korenmiklos** [comment]
Since there are no complaints, I am closing it as fixed.
