### ISSUE TITLE
Provide a directory of hard-coded logos

### ISSUE THREAD

**Issue by larsvilhuber** [social-science-data-editors/DCAS#31]
The dynamically generated logos via Shield.io are fine, but not robust, and may contravene certain site policies. 

Create a page with just the logos, which can then be downloaded by endorsers directly.

**Comment by korenmiklos** [comment]
I would keep this for now, change this once we have more than 1 version

**Comment by larsvilhuber** [comment]
This is not meant for us. The suggested code will not work for the typical journal website, unless also running Jekyll. If we want others to post, it must be simpler. The typical webmaster does not like to rely on images hosted elsewhere since they always​ break. They want to stick a copied image into their own directory. Making it easy increases acceptance.

Fine to leave as-is for now, but this is 1.1 high priority for adoption.

--
Lars Vilhuber, Economist
Cornell University
p: +1.607-330-5743
https://calendly.com/larsvilhuber
My working day may not be your working day. Please respond during your working day.
________________________________

**Comment by korenmiklos** [comment]
Good point. I can do it tonight.
