### ISSUE TITLE
Write launch "tweet"

### ISSUE THREAD

**Issue by larsvilhuber** [social-science-data-editors/DCAS#32]
Shorter variant of #4

**Comment by korenmiklos** [comment]
The data editors of @aeadata, @EJ_RES, @reveconstudies, @canjecon, and @InquiryWEAI launch the Data and Code Availability Standard http://datacodestandard.org/2022/12/15/launching-dcas.html DCAS describes an appropriate data and code replication package and helps authors comply with the journals' data policies.

**Comment by korenmiklos** [comment]
The data editors of @aeadata, @EJ_RES, @reveconstudies, @canjecon, and @InquiryWEAI launch the Data and Code Availability Standard http://datacodestandard.org/2022/12/15/launching-dcas.html DCAS describes an appropriate replication package and helps authors comply with journals' data and code availability policies

**Comment by korenmiklos** [comment]
If you agree with either version, please note and close this issue.

**Comment by larsvilhuber** [comment]
@tsalmon1 might object to being demoted from EIC...

**Comment by tsalmon1** [comment]
Not as much as you might think. Farasat can certainly represent us here but I can tweet this tomorrow from the EI account.

**Comment by larsvilhuber** [comment]
> The data editors of @aeadata, @EJ_RES, @reveconstudies, @canjecon, and @InquiryWEAI launch the Data and Code Availability Standard http://datacodestandard.org/2022/12/15/launching-dcas.html DCAS describes an appropriate replication package and helps authors comply with journals' data and code availability policies

I prefer this version.

**Comment by marieconnolly** [comment]
That's good with me! (Lars' preferred version)
