### ISSUE TITLE
Remove verb from badge

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#35]

**Comment by korenmiklos** [comment]
Pull this from shields.io via a Makefile

**Comment by larsvilhuber** [comment]
@korenmiklos any chance you will get to this soon?

**Comment by korenmiklos** [comment]
I will save new versions using [this URL](https://img.shields.io/badge/v1.0-brightgreen?style=plastic&logoWidth=40&labelColor=white&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAOCAYAAAEeda/MAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABvJJREFUSA1dVmuMXFUd///PvTP7pLszw7a7O3d2l507pU1t/VBAJVHqIwRIQAWigdAEQVBjoqaJiv0gNSZV1PCBSLB+UD74ChI0aRNNDNlCImLTphiyge7MsI+Z6W5357Hbfc7MPef4+9/ZW4knuXPO+b/fZ6ju+VOWiGue/y5hNUZuGa+NZjNyps1Mzlo65soZBNOyUzXt/0D2upd74Zp3yxE51zK5WdmFSgsHxL4hd+xF+pCI4gZECiJarbH9Vj4AVcPzQxzb8VutBshdmOH65OTAnsBdFYZNY2mgnGc5Q/JOP6suJbcqvBCgrGuj2TtxvyZnkYpzRXZ8DsybaaT946FJbagVoqqXe01MFCK5g+hZ2Zcy2Y800vs/KudwQWWwOOwPrXj+XRFMhLwCyc1MR9hqxs+ueTmr7PgBkf6H4aVC7WblnLdjt9qV8YMjLiv6EpGOK0WNTPYLA8opBGT/xbWM/zxZO9zF6pE+IHn+CotJDS/7O0v8MM4LTPZCPzuPbJH+4mCpeBa+a5i7gn1Q8KlyIRtZJlFdN+YtwItJ5RwPoxYhkcSlQUftawR8QCn9vtJ6YnBxtgQiE9F08lh58SbFT8eRCXFxnczpudLAqdvoUls8ahhN/TB2XZsTYfCEeSXjP8BMiVVjnhm6euUKtFOX685Fwmte7ozQ1UdLdyBHT7ec9rAoa2o+AJdPToxf9wXfMOYXyXKBrwd0EHl+npGA85ZszVHOdwcXZj4QIrgHXQCms7/F6T6ArjpKPTSwMPM/hfCWmJoIz7jwRKuW9n8D+APE9nKyVLxbWaZlIH1jTLGWzv0RwqW+rCSzR6nHcXwdsL5+xFS8EeU139/jMO2LMY/h7ggshHu5CxAOHnqBLH8cebyHpjp15qAof7qKchcGeHVxZ7d8LtLRGBhuLOAVEvwWimMNu6l52XPCIwS4W3yNiPhUx9hOSFaGDvXFuprrhumeHuK/b1vbgvtdEfGHd0nshtE/RvhGblLqq5JsUVL1sk/2sTqDWqRNaxrgT0ZJZtMbDKFUrDZ8DcJtL3M8EgrmUEBYQenc11HflKoUfwgBT+3AZ8T9YaJjvDzQ/XJvKc9bVn8NghPwZj5UILGNaZ1H5fDeSv4d8J/YtHYbYfu+KFkcHe2pp/0Hmc4HcUUvQehmpLwNBaiIPwtuZK31HTsx0Z0sF38NowLIbWG6SGda2jKGoF2mG/JOEts3e1l9shsdCgKqG33ZuMF9gya+eN3oB1PlzFlRUvVKTySUc8ZZGI3VvPJGQskUggRZN/fHdxV07qJIRtkaSgokP0M9h9NTQiQU+BFdVM/kfoU8SRgI1YQMh2h0o6UAFFsWwWb+SqKUfxlXIdEXjx6N3XbpUhtR+WXKcb7Z0DpIOK5b18EphPpHEV7kRzx1b/KwJfU2HOgVeGg3kC3YKCOpbtphbwruxkJknpLhDEU74RxDTiMknoFHBYbcbW1juFcz/ukIF+3gewb4J+UuhnT23Xcl4z+hMarQBU3QbOALZHQ1MESEbrdjwrJY9rI+6Nrr0AO6OcFHqzqSOwjdn5d7J3S7mMjzNW8yF5CaAdh0MasWmcOuiS22OZC3gpF6hS74zFClOGURWUZkRQT4Ie8YjD4vZaJ3YWEGqpn9t8esveACgRr8T72bPpbcsbNxViOIqNZkDu4tf5CPbCh5Xk8fdc8ju0PSFFhtSP8LE/+VnfbfEnNzq6Lv/x0QgF3ad6TPjW0VYMkw2hQlpe81xp3tc8z76EAR1sIc359YnJ3HTQbXjVkuyGjtKrCrY2MJbeJFyEvAK1QFHU4tFKaXM7lPoTbewENOMHJhaaArd2h6uiV8kCG2mPqof79VdBL322GLI70kylB+VA+CE3ht5UHtfHToUDjU4u7WtwaUwqwn6YdKvZun5H2A8dOYnoTnPG4c9ROgwyXDUGREd9nBG5aCnAMT/0ecORG+lpa/IcZLhPeW8m82rX22FyHowVQeXm2eE3os4RX1lLxaOIse+QQ+V+bdjuNMAhGs6kDcPM2dUcNpZhtgvB1Byj4rHiYdh+ravJ4q5z8HhjAzIhD0/04p546a0U3Mwi449S7q5TKi1Q2Vd+5RypOmrmlz/1Alf66K96oXT4pYs2PNa6ly8aEpOPtpjC3AwuzJe+cy3xUH36bVPwfN95Yz2S8PsfunNoTieS8h8ecwfTbgl/xFGId9qqb1c/KP7j3QYBiSYcsNjOR3QPz7VKXwthgcKZHzK2hK+VMiZ/w1OA6vHoPhOVzx1NEGHJ+HnFdTpcJLYfq97L2QhfTzNmhnEuXCtwEP+UUGZIeBkZKNxbdfxAs6AjAmqz2ZXCj+c2NiYrgZuDJE7sY3Bg5lLS8iPa8mKoXnRMd/AbCzW8/QF3NOAAAAAElFTkSuQmCC).
