### ISSUE TITLE
Write launch "press release"

### ISSUE THREAD

**Issue by korenmiklos** [social-science-data-editors/DCAS#4]

**Comment by marieconnolly** [comment]
The data editors of the journals of the American Economic Association, the Econometrics Journal, the Economic Journal, the Review of Economic Studies, and the Canadian Journal of Economics come together to proudly launch DCAS, the Data and Code Availability Standard. This set of rules regarding what constitutes an appropriate data and code replication package will help authors comply with the journals’ data and code availability policies. DCAS provides a standard, meant to make compliance easier by setting common requirements across journals, and to help journals craft their own data and code availability policy.

**Comment by larsvilhuber** [comment]
Also https://github.com/social-science-data-editors/DCAS/commit/6aa48cdffc3f3acac0a17c43adf656f63ac93007

**Comment by korenmiklos** [comment]
@larsvilhuber Are we adding JPE Micro?

**Comment by larsvilhuber** [comment]
Ask Anna, not me. She said after launch.

--
Lars Vilhuber
On mobile device
________________________________

**Comment by korenmiklos** [comment]
Ok, that's how I understood. I am closing this and removing other endorsement issues out of milestone. 

We are ready to launch.
