### ISSUE TITLE
Archiving and DOI

### ISSUE THREAD

**Issue by larsvilhuber** [social-science-data-editors/DCAS#8]
Needs to be archived to Zenodo.

- Suggestion: archive the rendered HTML separately,  (for easier consumption)
- Suggestion: (hard) PDF as well
- Definitely archive  the source code (separately, automatically)

**Comment by korenmiklos** [comment]
@larsvilhuber Should this all be one record on Zenodo? I now have a single PDF printout of the DCASE page.

**Comment by korenmiklos** [comment]
Published https://zenodo.org/record/7436134
